name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '*.md'
      
  pull_request:
     branches:
      - master
      - dev
     types:
      - opened
      - synchronize
     paths-ignore:
      - '*.md'

jobs:
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9.2
          
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          
      - name: Install dependencies
        run: pipenv install --dev
          
      - name: Lint with flake8
        run: pipenv run lint