name: Deploy to Heroku

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            SCREEN_NAME
            CK
            AT
            ATS
        env:
          SCREEN_NAME: ${{ secrets.SCREEN_NAME }}
          CK: ${{ secrets.CK }}
          CS: ${{ secrets.CS }}
          AT: ${{ secrets.AT }}
          ATS: ${{ secrets.ATS }}