name: Lint

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
      
  pull_request:
     branches:
      - master
      - dev
     types:
      - opened
      - synchronize
     paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'

jobs:
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9.6
          
      - name: Install Pip && Depends
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir
          
      - name: Lint with flake8
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
